# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('company', 'Company'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('birth_place', models.CharField(max_length=200)),
                ('birth_date', models.CharField(max_length=200)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('website', models.URLField()),
                ('origin', models.CharField(choices=[('english', 'English publisher'), ('original', 'Original publisher')], default='original', max_length=10)),
                ('state', models.CharField(choices=[('defunct', 'Defunct'), ('active', 'Active'), ('active', 'Unknown')], default='active', max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='blog.Category'),
        ),
    ]
