# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170325_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='state',
            field=models.CharField(choices=[('defunct', 'Defunct'), ('active', 'Active'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
