# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170325_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
