# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170326_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='origin',
            field=models.CharField(choices=[('English', 'English publisher'), ('Original', 'Original publisher')], default='Original', max_length=10),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state',
            field=models.CharField(choices=[('Defunct', 'Defunct'), ('Active', 'Active'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='serie',
            name='edition',
            field=models.CharField(choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback'), ('Comic-book', 'Comic-book'), ('Digital', 'Digital'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='serie',
            name='orig_state',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Unknown', 'Unknown')], default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='serie',
            name='state',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Dropped', 'Dropped'), ('Axed', 'Axed (origin)'), ('Unknown', 'Unknown')], default='Unknown', max_length=15),
        ),
    ]
