# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170326_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='demography',
            options={'verbose_name_plural': 'demographies'},
        ),
        migrations.AlterField(
            model_name='serie',
            name='edition_comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='original_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
