# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170524_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='a_date',
            field=models.DateField(verbose_name='announcement date'),
        ),
    ]
